
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 2500

logging:
  level:
    com.example: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
